# PLACEHOLDER-BEGIN #
MESSAGE("-- functions.cmake")

macro(INCLUDE_CMAKE_FILE)
    IF(EXISTS ${ARGV0})
        MESSAGE("INCLUDING: ${ARGV0}")
        INCLUDE(${ARGV0})
    ELSE()
        MESSAGE("NOT INCLUDING: ${ARGV0} - FILE DOESN'T EXIST")
    ENDIF()
endmacro()

macro(INCLUDE_DIRECTORIES_WINDOWS)
    IF (WIN32)
        INCLUDE_DIRECTORIES(${ARGV0})
    ENDIF()
endmacro()

# PLACEHOLDER-END #
