# PLACEHOLDER-BEGIN #
MESSAGE("-- functions.cmake")

function(INCLUDE_CMAKE_FILE)
    IF(EXISTS ${ARGV0})
        MESSAGE("INCLUDING: ${ARGV0}")
        INCLUDE(${ARGV0})
    ELSE()
        MESSAGE("NOT INCLUDING: ${ARGV0} - FILE DOESNT EXIST")
    ENDIF()
endfunction()

function(INCLUDE_DIRECTORIES_WINDOWS)
    IF (WIN32)
        INCLUDE_DIRECTORIES(${ARGV0})
    ENDIF()
endfunction()

INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/functions.cmake)
INCLUDE_CMAKE_FILE(${MAIN_SH_CMAKE_PATH}/functions.cmake)

# PLACEHOLDER-END #
