# PLACEHOLDER-BEGIN #
MESSAGE("-- lib.cmake")

INCLUDE_CMAKE_FILE(${MAIN_CMAKE_PATH}/sh/lib.cmake)
INCLUDE_CMAKE_FILE(${MAIN_CMAKE_PATH}/cpp/lib.cmake)

IF(DISTRIBUTION STREQUAL "FreeBSD")
    INSTALL(FILES "${LIBRARY_OUTPUT_PATH}/freebsd.sh"                DESTINATION lib)
ENDIF()

# PLACEHOLDER-END #
