# PLACEHOLDER-BEGIN #
MESSAGE("-- lib.cmake")

INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/lib.cmake)
INCLUDE_CMAKE_FILE(${MAIN_SH_CMAKE_PATH}/lib.cmake)

IF(DISTRIBUTION STREQUAL "FreeBSD")
    INSTALL(FILES "${LIBRARY_OUTPUT_PATH}/freebsd.sh"                DESTINATION lib)
ENDIF()

# PLACEHOLDER-END #
