# PLACEHOLDER-BEGIN #
MESSAGE("-- packaging.cmake")

# Binary packages or non-binary (scripts, Java, Python) packages.
SET(MACHINE_BINARY_PROJECT FALSE)
SET(CPACK_RPM_SPEC_MORE_DEFINE "%undefine __brp_mangle_shebangs")

IF(MACHINE_BINARY_PROJECT)
    SET(ARCH_TYPE_SUFFIX "${CMAKE_SYSTEM_PROCESSOR}")
    SET(DEBIAN_ARCH_TYPE_SUFFIX "all")
ELSE ()
    SET(ARCH_TYPE_SUFFIX "noarch")
    SET(DEBIAN_ARCH_TYPE_SUFFIX "all")# or "any" - https://www.debian.org/doc/debian-policy/ch-customized-programs.html#s-arch-spec
ENDIF()

# https://cmake.org/cmake/help/v4.1/manual/cpack-generators.7.html
SET(CPACK_PACKAGE_NAME                    "${PROJECT_NAME}")
SET(CPACK_PACKAGE_VENDOR                  "${PROJECT_VENDOR}")
SET(CPACK_PACKAGE_DESCRIPTION             "${PROJECT_DESCRIPTION}")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY     "${PROJECT_DESCRIPTION_SUMMARY}")
SET(CPACK_PACKAGE_VERSION                 "${PROJECT_VERSION}")
SET(CPACK_PACKAGE_FILE_NAME               "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}.${ARCH_TYPE_SUFFIX}")
SET(CPACK_PACKAGE_VERSION_MAJOR           "${PROJECT_VERSION_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR           "${PROJECT_VERSION_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH           "${PROJECT_VERSION_PATCH}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY       "CPack Component Example")
SET(CPACK_PACKAGING_INSTALL_PREFIX        ${CMAKE_INSTALL_PREFIX})
SET(CPACK_PACKAGE_RELOCATABLE             TRUE)

# https://cmake.org/cmake/help/v4.1/cpack_gen/rpm.html
SET(CPACK_RPM_PACKAGE_NAME                ${PROJECT_NAME})
SET(CPACK_RPM_PACKAGE_DESCRIPTION         "${PROJECT_DESCRIPTION}")
SET(CPACK_RPM_PACKAGE_LICENSE             "MIT")
SET(CPACK_RPM_PACKAGE_DEBUG               true)
SET(CPACK_RPM_PRE_INSTALL_SCRIPT_FILE     "${RPM_INSTALL_SCRIPTS_PATH}/pre.install.sh")
SET(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE   "${RPM_INSTALL_SCRIPTS_PATH}/pre.uninstall.sh")
SET(CPACK_RPM_POST_INSTALL_SCRIPT_FILE    "${RPM_INSTALL_SCRIPTS_PATH}/post.install.sh")
SET(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE  "${RPM_INSTALL_SCRIPTS_PATH}/post.uninstall.sh")
SET(CPACK_RPM_PACKAGE_SUMMARY             "Summary")
SET(CPACK_RPM_CHANGELOG_FILE              ${CHANGE_LOG_FILE_NAME})
SET(CPACK_RPM_PACKAGE_ARCHITECTURE        ${ARCH_TYPE_SUFFIX})
# SET(CPACK_RPM_PACKAGE_REQUIRES            "some-else >= 1.0.0")

# https://cmake.org/cmake/help/v4.1/cpack_gen/deb.html
# http://www.debian.org/doc/debian-policy/ch-controlfields.html
# https://wiki.ubuntu.com/PackagingGuide/Basic?action=show&redirect=HowToBuildDebianPackagesFromScratch/
SET(CPACK_DEBIAN_PACKAGE_NAME             "${PROJECT_NAME}")
SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION      "${PROJECT_DESCRIPTION}")
SET(CPACK_DEBIAN_PACKAGE_VERSION          "${CPACK_PACKAGE_VERSION}")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER       "${PROJECT_MAINTAINER}")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY         "optional")
SET(CPACK_DEBIAN_PACKAGE_SECTION          "libs")
SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA    "${DEB_INSTALL_SCRIPTS_PATH}/preinst" "${DEB_INSTALL_SCRIPTS_PATH}/prerm" "${DEB_INSTALL_SCRIPTS_PATH}/postinst" "${DEB_INSTALL_SCRIPTS_PATH}/postrm")
SET(CPACK_DEBIAN_ARCHITECTURE             "${DEBIAN_ARCH_TYPE_SUFFIX}")
#SET(CPACK_DEBIAN_PACKAGE_DEPENDS          "some-else (>= 1.0.0)")

# https://cmake.org/cmake/help/v4.1/cpack_gen/freebsd.html
SET(CPACK_FREEBSD_PACKAGE_NAME            "${PROJECT_NAME}")
SET(CPACK_FREEBSD_PACKAGE_COMMENT         "${PROJECT_DESCRIPTION_SUMMARY}")
SET(CPACK_FREEBSD_PACKAGE_DESCRIPTION     "${PROJECT_DESCRIPTION}")
SET(CPACK_FREEBSD_PACKAGE_WWW             "${PROJECT_WWW}")
SET(CPACK_FREEBSD_PACKAGE_LICENSE         "${PROJECT_LICENSE}")
SET(CPACK_FREEBSD_PACKAGE_LICENSE_LOGIC   "single")
SET(CPACK_FREEBSD_PACKAGE_MAINTAINER      ${PROJECT_MAINTAINER})
SET(CPACK_FREEBSD_PACKAGE_ORIGIN          "misc/${PROJECT_NAME}")
SET(CPACK_FREEBSD_PACKAGE_CATEGORIES      "libs")
SET(CPACK_FREEBSD_PACKAGE_DEPS            "")

# https://cmake.org/cmake/help/v4.1/cpack_gen/nsis.html
SET(CPACK_NSIS_DISPLAY_NAME               "NSIS Display name")
SET(CPACK_NSIS_PACKAGE_NAME               "NSIS Package name")
SET(CPACK_NSIS_INSTALLED_ICON_NAME        "${APP_LOW_NAME}.ico")
SET(CPACK_NSIS_HELP_LINK                  ${APP_URL})
SET(CPACK_NSIS_URL_INFO_ABOUT             ${APP_URL})
SET(CPACK_NSIS_CONTACT                    ${APP_EMAIL})

# https://cmake.org/cmake/help/v4.1/cpack_gen/dmg.html
SET(CPACK_DMG_VOLUME_NAME                 "${PROJECT_NAME} Installer")
SET(CPACK_DMG_FORMAT                      "UDBZ")
SET(CPACK_DMG_DISABLE_APPLICATIONS_SYMLINK OFF)
#SET(CPACK_DMG_DS_STORE                    "${CMAKE_BINARY_DIR}/_CPack_Packages/DMG_DS_Store")
#SET(CPACK_DMG_SLA_LANGUAGES               "English")
#SET(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE OFF)
#SET(CPACK_PACKAGE_FILE_NAME               "${PROJECT_NAME}-${PROJECT_VERSION}-macos")
#SET(CPACK_DMG_BACKGROUND_IMAGE            "${CMAKE_SOURCE_DIR}/assets/dmg-background.png")
#SET(CPACK_DMG_DS_STORE_SETUP_SCRIPT       "${CMAKE_SOURCE_DIR}/dmg_setup.scpt")
# SET(CPACK_DMG_APPLE_FILESYSTEM "HFS+")

IF (WIN32)
    SET(CPACK_GENERATOR                       "${DEFAULT_PACKAGES};NSIS")
ENDIF()
IF(DISTRIBUTION STREQUAL "RedHat")
    SET(CPACK_GENERATOR                       "${DEFAULT_PACKAGES};RPM")
ENDIF()
IF(DISTRIBUTION STREQUAL "Debian")
    SET(CPACK_GENERATOR                       "${DEFAULT_PACKAGES};DEB")
ENDIF()
IF(DISTRIBUTION STREQUAL "FreeBSD")
    # What is proper value for that?
    #SET(CPACK_GENERATOR                       "${DEFAULT_PACKAGES};FREEBSD")
    SET(CPACK_GENERATOR                       "${DEFAULT_PACKAGES}")
ENDIF()
IF(DISTRIBUTION STREQUAL "MacOS")
    SET(CPACK_GENERATOR                       "${DEFAULT_PACKAGES};DragNDrop")
ENDIF()

# PLACEHOLDER-PRE-PACK#

include(CPack)

# PLACEHOLDER-END #
