.TH another "1" "February 2019" "Example Man 1.0.0" "Example Man Command"
.SH NAME
another \- short description
.SH SYNOPSIS
.B another
[\fIxxxx\fR]... [\fIyyyyy\fR]...
.SH DESCRIPTION
.PP
.I another
is a template for man pages.
The command does something with \fB\-part xxx\fR or \fB\-\-part yyyy\fR.
.PP
More description. More and more and more.
.PP
Some additional description.
.PP
And some more additional description.
.SH OPTIONS
.TP
\fB\-one\fR, \fB\-\-one\fR
do not ignore entries starting with .
.TP
\fB\-two\fR, \fB\-\-two\-two\fR
do not list implied . and ..
.PP
Description of options.
.SH EXAMPLES
.PP
Examples of usage.
.SH OTHER
.PP
Other relevant information.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report another bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
See also
.B another.command
manual. The manual is maintained as a Texinfo manual.
.B some another tools
.PP
The command \fBxxx.command\fR invocation
should give you access to the complete manual.
