.TH base64decode "1" "February 2019" "SMI Toolset 0.100.0" "SMI Base64 Command"
.SH NAME
base64decode \- Decode base64 encoded string
.SH SYNOPSIS
.B base64decode
.I "STRING"
.SH DESCRIPTION
.PP
.B base64decode
decodes a base64 encoded string provided as an argument using a Python helper script.
.SH EXAMPLES
.PP
base64decode SGVsbG8gV29ybGQ=
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report base64decode bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR base64encode (1)

