.TH base64encode "1" "February 2019" "SMI Toolset 0.100.0" "SMI Base64 Command"
.SH NAME
base64encode \- Encode string to base64
.SH SYNOPSIS
.B base64encode
.I "STRING"
.SH DESCRIPTION
.PP
.B base64encode
encodes a string provided as an argument into base64 format using a Python helper script.
.SH EXAMPLES
.PP
base64encode "Hello World"
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report base64encode bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR base64decode (1)

