.TH hgrep "1" "October 2025" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
hgrep \- Search bash history for a pattern
.SH SYNOPSIS
.B hgrep
.I PATTERN
.SH DESCRIPTION
.PP
.B hgrep
is a utility script that searches the user's bash history file (\fB~/.bash_history\fR) for the specified \fIPATTERN\fR using \fBgrep\fR.
.SH EXAMPLES
.PP
hgrep "smi-docker"
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report hgrep bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR grep (1)
