.TH microserviced "8" "October 2025" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
microserviced \- setmy.info microservice daemon (FreeBSD)
.SH SYNOPSIS
.B microserviced
.RI [ start|stop|restart|status ]
.SH DESCRIPTION
.PP
.B microserviced
is a FreeBSD rc script for managing the microservice daemon. It uses \fB/usr/sbin/daemon\fR to run the service in the background and manage its PID files and logging.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report microserviced bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR microservice (1)

