.TH quicklisp-setup "1" "February 2023" "quicklisp-setup Man 1.0.0" "quicklisp-setup"
.SH NAME
quicklisp-setup \- root user quicklisp download tool.
.SH SYNOPSIS
.B quicklisp-setup
.SH DESCRIPTION
.PP
The
.B quicklisp-setup
command downloads Quicklisp under \fB/opt/quicklisp/lib\fR.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
See also
.B another.command
manual. The manual is maintained as a Texinfo manual.
.B some another tools
.PP
The command \fBxxx.command\fR invocation
should give you access to the complete manual.
