.TH radians "1" "February 2019" "SMI Toolset 0.100.0" "SMI Math Command"
.SH NAME
radians \- Convert degrees to radians
.SH SYNOPSIS
.B radians
.I DEGREES
.SH DESCRIPTION
.PP
.B radians
converts the given degrees value to radians using a Groovy helper script.
.SH EXAMPLES
.PP
radians 180
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report radians bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR degrees (1)

