.TH smi-organization-dir-location "1" "October 2025" "SMI Toolset 0.100.0" "SMI Gintra Command"
.SH NAME
smi-organization-dir-location \- Print the path to a directory within an organization
.SH SYNOPSIS
.B smi-organization-dir-location
.I COUNTRY_CODE
.I ORG_SHORT_NAME
.I DIRECTORY_NAME
.SH DESCRIPTION
.PP
.B smi-organization-dir-location
prints the path to a specific sub-directory within an organization's directory. It uses the provided ISO 3166-1 alpha-2 \fICOUNTRY_CODE\fR, \fIORG_SHORT_NAME\fR, and \fIDIRECTORY_NAME\fR to construct the path.
.SH EXAMPLES
.PP
smi-organization-dir-location EE setmy.info bin
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-organization-dir-location bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-organization-location (1)

