.TH smi-net-location "1" "October 2025" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
smi-net-location \- Print the SMI network directory path (Deprecated)
.SH SYNOPSIS
.B smi-net-location
.SH DESCRIPTION
.PP
.B smi-net-location
is a deprecated command that prints the path to the network directory within the SMI variable data location.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report smi-net-location bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-var-location (1)

