.TH smi-man-location "1" "October 2025" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
smi-man-location \- Print the SMI manual page directory location
.SH SYNOPSIS
.B smi-man-location
.SH DESCRIPTION
.PP
.B smi-man-location
prints the absolute path to the directory where SMI manual pages are located.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-man-location bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-location (1),
.BR smi-bin-location (1),
.BR smi-lib-location (1)

