.TH smi-etc-location "1" "February 2026" "SMI Toolset" "SMI Etc Location Command"
.SH NAME
smi-etc-location \- print the SMI configuration directory path
.SH SYNOPSIS
.B smi-etc-location
.SH DESCRIPTION
.PP
The
.B smi-etc-location
command prints the path to the SMI configuration directory.
The output may vary depending on the operating system (e.g., FreeBSD vs Linux).
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-location (1)
