.TH smi-provider "1" "February 2026" "SMI Toolset" "SMI Provider Command"
.SH NAME
smi-provider \- print the provider name of the SMI toolset
.SH SYNOPSIS
.B smi-provider
.SH DESCRIPTION
.PP
The
.B smi-provider
command prints the provider name of the SMI toolset to standard output.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-version (1)
