.TH smi-temp-location "1" "February 2026" "SMI Toolset" "SMI Temp Location Command"
.SH NAME
smi-temp-location \- print the SMI temporary directory path
.SH SYNOPSIS
.B smi-temp-location
.SH DESCRIPTION
.PP
The
.B smi-temp-location
command prints the path to the SMI temporary directory.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-location (1)
