.TH smi-home-packages-location "1" "October 2025" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
smi-home-packages-location \- Print the user's SMI packages directory location
.SH SYNOPSIS
.B smi-home-packages-location
.SH DESCRIPTION
.PP
.B smi-home-packages-location
prints the absolute path to the \fBpackages\fR directory within the user's SMI home directory (see \fBsmi-home-location\fR(1)).
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report smi-home-packages-location bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-home-location (1),
.BR smi-packages-location (1)

