.TH smi-location "1" "February 2026" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
smi-location \- Print the SMI installation prefix location
.SH SYNOPSIS
.B smi-location
.SH DESCRIPTION
.PP
The \fBsmi-location\fR command prints the absolute path to the SMI installation prefix directory.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-bin-location (1),
.BR smi-lib-location (1)
