.TH smi-var-location "1" "February 2026" "SMI Toolset" "SMI Var Location Command"
.SH NAME
smi-var-location \- print the SMI variable data directory path
.SH SYNOPSIS
.B smi-var-location
.SH DESCRIPTION
.PP
The
.B smi-var-location
command prints the path to the SMI variable data directory.
The output may vary depending on the operating system.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-location (1)
