.TH smi-version "1" "February 2026" "SMI Toolset" "SMI Version Command"
.SH NAME
smi-version \- print the version of the SMI toolset
.SH SYNOPSIS
.B smi-version
.SH DESCRIPTION
.PP
The
.B smi-version
command prints the current version of the SMI toolset to standard output.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-provider (1)
