.TH smi-bin-location "1" "February 2026" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
smi-bin-location \- Print the SMI binary directory location
.SH SYNOPSIS
.B smi-bin-location
.SH DESCRIPTION
.PP
The \fBsmi-bin-location\fR command prints the absolute path to the directory where SMI executable scripts are located.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-location (1),
.BR smi-lib-location (1)
