.TH smi-home-location "1" "February 2026" "SMI Toolset" "SMI Home Location Command"
.SH NAME
smi-home-location \- print the SMI user home directory path
.SH SYNOPSIS
.B smi-home-location
.SH DESCRIPTION
.PP
The
.B smi-home-location
command prints the path to the user's SMI-specific home directory,
which is typically located at \fB~/.${SMI_PROVIDER_NAME}\fR.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-provider (1)
