.TH smi-lib-location "1" "February 2026" "SMI Toolset" "SMI Lib Location Command"
.SH NAME
smi-lib-location \- print the SMI library directory path
.SH SYNOPSIS
.B smi-lib-location
.SH DESCRIPTION
.PP
The
.B smi-lib-location
command prints the path to the SMI library directory.
.SH AUTHOR
.PP
Command written by Imre Tabur.
.PP
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report bugs to \fIinfo@setmy.info\fR.
.SH "SEE ALSO"
.PP
.BR smi-include (1)
