.TH smi-download-package "1" "April 2026" "SMI Toolset" "SMI Base Command"
.SH NAME
smi-download-package \- Download one or more SMI packages
.SH SYNOPSIS
.B smi-download-package
.I PACKAGE_NAME...
.SH DESCRIPTION
.PP
.B smi-download-package
downloads the specified SMI packages to the packages download directory (see \fBsmi-home-packages-location\fR(1)).
It uses the \fBpackages.sh\fR library to locate package definitions (with \fB.package\fR suffix) in either the system or home packages directories and executes their respective download functions.
.PP
The download directory defaults to \fB~/.setmy.info/packages\fR but can be overridden by setting the
\fBSMI_HOME_PACKAGES_DIR\fR environment variable before invoking this command.
.SH ENVIRONMENT
.TP
.B SMI_HOME_PACKAGES_DIR
Overrides the default packages download directory.
See \fBsmi-home-packages-location\fR(1) for details.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-download-package bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-install-package (1),
.BR smi-packages-location (1),
.BR smi-home-packages-location (1)

