.TH smi-nodes-location "1" "October 2025" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
smi-nodes-location \- Print the SMI nodes configuration path (Deprecated)
.SH SYNOPSIS
.B smi-nodes-location
.SH DESCRIPTION
.PP
.B smi-nodes-location
is a deprecated command that prints the path to the nodes configuration directory within the SMI localhost location.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-nodes-location bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-localhost-location (1)

