.TH smi "1" "October 2025" "SMI Toolset 0.100.0" "SMI Base Command"
.SH NAME
smi \- Central SMI command (Work In Progress)
.SH SYNOPSIS
.B smi
.SH DESCRIPTION
.PP
.B smi
is intended to be the central command for the SMI toolset. It is currently a placeholder (TODO).
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-version (1)

