.TH tab "1" "February 2026" "SMI Toolset 0.100.0" "SMI Workstation Command"
.SH NAME
tab \- Open one or more URLs in new Firefox tabs
.SH SYNOPSIS
.B tab
.I URL...
.SH DESCRIPTION
.PP
.B tab
opens the specified URL(s) in new tabs of the Firefox browser.
.PP
If multiple URLs are provided, each will be opened in its own new tab.
.PP
On Unix-like systems, it calls \fI/opt/firefox/firefox\fR.
On Windows, it calls \fI"C:\\Program Files\\Mozilla Firefox\\firefox.exe"\fR.
.SH EXAMPLES
.B tab
.I https://www.google.com
.PP
.B tab
.I https://www.google.com https://www.github.com
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report tab bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR firefox (1),
.BR tabs (1)
