.TH uuid "1" "February 2019" "SMI Toolset 0.100.0" "SMI Utility Command"
.SH NAME
uuid \- Generate a UUID
.SH SYNOPSIS
.B uuid
.SH DESCRIPTION
.PP
.B uuid
generates a Universally Unique Identifier (UUID) using a Groovy helper script.
.SH EXAMPLES
.PP
uuid
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report uuid bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-timestamp (1)

