.TH versions "1" "February 2019" "SMI Toolset 0.100.0" "SMI Utility Command"
.SH NAME
versions \- Print versions of installed development tools
.SH SYNOPSIS
.B versions
.SH DESCRIPTION
.PP
.B versions
is a utility script that prints the version information for various development tools installed on the system, including Maven, Gradle, CMake, Leiningen, Groovy, Go, Julia, Node.js, Java, Python, Kubectl, Micronaut, Grails, and Argo.
.SH EXAMPLES
.PP
versions
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report versions bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-version (1)

