# PLACEHOLDER-BEGIN #
MESSAGE("-- test cpp targets.cmake")

#ADD_EXECUTABLE(test.bin         ${GLOBAL_MODULE_TEST_SOURCES})

#TARGET_LINK_LIBRARIES(test.bin  "${EXAMPLE_TEST_LINKING}")

#INCLUDE_CMAKE_FILE(${TEST_CPP_CMAKE_PATH}/tests.cmake)

# PLACEHOLDER-END #
