# PLACEHOLDER-BEGIN #
MESSAGE("-- vcs bin.cmake")

INSTALL(PROGRAMS  "${BINARY_OUTPUT_PATH}/difftool"  DESTINATION bin)
INSTALL(PROGRAMS  "${BINARY_OUTPUT_PATH}/difftoolc" DESTINATION bin)
INSTALL(PROGRAMS  "${BINARY_OUTPUT_PATH}/difftools" DESTINATION bin)

# PLACEHOLDER-END #
