# PLACEHOLDER-BEGIN #
MESSAGE("-- hello bin.cmake")

INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/hello-elixir" DESTINATION bin)
INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/hello-lisp"   DESTINATION bin)

# PLACEHOLDER-END #
