# PLACEHOLDER-BEGIN #
MESSAGE("-- hello variables.cmake")

SET (MAIN_ELIXIR_SOURCES_PATH ${MAIN_SOURCES_PATH}/elixir)
SET (HELLO_MAN_SOURCES_PATH   ${MAIN_MAN_SOURCES_PATH}/hello)

# PLACEHOLDER-END #
