REM set LEININGEN_HOME=%PUB_DIR%\lein
REM set LEININGEN_BIN_DIR="%LEININGEN_HOME%\bin"
REM set LEININGEN_LIB_DIR="%LEININGEN_HOME%\lib"
REM set LEIN_JAR=%LEININGEN_LIB_DIR%\leiningen-2.9.10.jar
REM set PATH=%LEININGEN_BIN_DIR%;%PATH%
