STEALER_DIR=${CUR_DIR}/.stealer
REPOS_DIR=${STEALER_DIR}/repos
PROJECTS_NAMES=`ls ${REPOS_DIR} | sort`
PATCH_DIR=${STEALER_DIR}/patch
CHECKOUT_DIR=${STEALER_DIR}/checkout
CHECKOUT_ORIGINAL_DIR=${CHECKOUT_DIR}/original
CLEANED_DIR=${CHECKOUT_DIR}/cleaned
