STEALER_DIR=${CUR_DIR}/.stealer
REPOS_DIR=${STEALER_DIR}/repos
PROJECTS_NAMES=`ls ${REPOS_DIR} | sort`
PATCH_DIR=${STEALER_DIR}/patch
CLONE_DIR=${STEALER_DIR}/clone
CLONE_ORIGINAL_DIR=${CLONE_DIR}/original
CLEANED_DIR=${CLONE_DIR}/cleaned
