# PLACEHOLDER-BEGIN #
MESSAGE("-- ai bin.cmake")

INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/ai"                   DESTINATION bin)
INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/ai-profiles-location" DESTINATION bin)

IF (WIN32)
    INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/ai.cmd" DESTINATION bin)
ENDIF()

# PLACEHOLDER-END #
