# PLACEHOLDER-BEGIN #
MESSAGE("-- ai bin.cmake")

INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/ai"                   DESTINATION bin)
INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/ai-profiles-location" DESTINATION bin)

# PLACEHOLDER-END #
