# PLACEHOLDER-BEGIN #
MESSAGE("-- ai bin.cmake")

INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/ai"               DESTINATION bin)
INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/smi-build-tasklist" DESTINATION bin)
INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/smi-agent"          DESTINATION bin)
INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/smi-agent-cli"      DESTINATION bin)
INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/smi-agent-cli-options" DESTINATION bin)

IF (WIN32)
    INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/ai.cmd" DESTINATION bin)
    INSTALL(PROGRAMS "${BINARY_OUTPUT_PATH}/smi-build-tasklist.cmd" DESTINATION bin)
ENDIF()

# PLACEHOLDER-END #
