# PLACEHOLDER-BEGIN #
MESSAGE("-- ai lib.cmake")

INSTALL(DIRECTORY "${LIBRARY_OUTPUT_PATH}/profiles/ai" DESTINATION lib/profiles)
INSTALL(FILES "${LIBRARY_OUTPUT_PATH}/ai-profiles.sh"  DESTINATION lib)

# PLACEHOLDER-END #
