# PLACEHOLDER-BEGIN #
MESSAGE("-- ai lib.cmake")

FILE(GLOB SH_AI_PROFILES "${MAIN_SH_SOURCES_PATH}/ai/lib/*.md")
FILE(GLOB SH_AI_GROUPS "${MAIN_SH_SOURCES_PATH}/ai/lib/*.group")
INSTALL(FILES ${SH_AI_PROFILES} ${SH_AI_GROUPS} DESTINATION lib/ai)

# PLACEHOLDER-END #
