set JENKINS_DATA_HOME=%USERPROFILE%\.jenkins
set JENKINS_LIB_DIR=%SMI_LIB_DIR%
set JENKINS_WAR=%JENKINS_LIB_DIR%\jenkins.war
set JENKINS_CLI_JAR=%JENKINS_LIB_DIR%\jenkins-cli.jar
set JENKINS_AGENT_JAR=%JENKINS_LIB_DIR%\jenkins-agent.jar
