set JENKINS_DIR=%PUB_DIR%\jenkins
set JENKINS_LIB_DIR=%JENKINS_DIR%
set JENKINS_WAR=%JENKINS_LIB_DIR%\jenkins.war
set JENKINS_CLI_JAR=%JENKINS_LIB_DIR%\jenkins-cli.jar
set JENKINS_AGENT_JAR=%JENKINS_LIB_DIR%\agent.jar
