set CLOJURE_SCRIPT_HOME=%PUB_DIR%\clojurescript
set CLOJURE_BIN_DIR="%CLOJURE_SCRIPT_HOME%\bin"
set CLOJURE_LIB_DIR="%CLOJURE_SCRIPT_HOME%\lib"
set CLOJURE_JAR=%CLOJURE_LIB_DIR%\cljs.jar
set PATH=%CLOJURE_BIN_DIR%;%PATH%