REM set JAVA_HOME=%PUB_DIR%\jdk-17
REM set JAVA_HOME=%PUB_DIR%\jdk-18.0.1.1
REM set JAVA_HOME=%PUB_DIR%\jdk-19
set JAVA_HOME=%PUB_DIR%\jdk-19.0.1
set JAVA_BIN_DIR=%JAVA_HOME%\bin
set PATH=%JAVA_BIN_DIR%;%PATH%
