# PLACEHOLDER-BEGIN #
MESSAGE("-- infra lib.cmake")

INSTALL(DIRECTORY "${LIBRARY_OUTPUT_PATH}/k8s"   DESTINATION lib)
INSTALL(DIRECTORY "${LIBRARY_OUTPUT_PATH}/argo"  DESTINATION lib)

# PLACEHOLDER-END #
