# PLACEHOLDER-BEGIN #
MESSAGE("-- infra targets.cmake")

SET (MAIN_K8S_SOURCES_PATH   ${MAIN_SOURCES_PATH}/k8s)
SET (MAIN_ARGO_SOURCES_PATH  ${MAIN_SOURCES_PATH}/argo)
SET (K8S_OUTPUT_PATH         ${LIBRARY_OUTPUT_PATH}/k8s)
SET (ARGO_OUTPUT_PATH        ${LIBRARY_OUTPUT_PATH}/argo)

ADD_CUSTOM_TARGET(buildK8sYaml
    COMMAND ${CMAKE_COMMAND} -E make_directory ${K8S_OUTPUT_PATH}
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${MAIN_K8S_SOURCES_PATH} ${K8S_OUTPUT_PATH}
)

ADD_CUSTOM_TARGET(buildArgoYaml
    COMMAND ${CMAKE_COMMAND} -E make_directory ${ARGO_OUTPUT_PATH}
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${MAIN_ARGO_SOURCES_PATH} ${ARGO_OUTPUT_PATH}
)

SET (INFRA_MAN_SOURCES_PATH ${MAIN_MAN_SOURCES_PATH}/infra)

ADD_CUSTOM_TARGET(buildInfraMan cp ${INFRA_MAN_SOURCES_PATH}/man1/*.1 ${MAN_OUTPUT_PATH}/man1 && gzip -f ${MAN_OUTPUT_PATH}/man1/*.1)

# PLACEHOLDER-END #
