# PLACEHOLDER-BEGIN #
MESSAGE("-- base variables.cmake")

SET (BASE_MAN_SOURCES_PATH ${MAIN_MAN_SOURCES_PATH}/base PARENT_SCOPE)

MESSAGE("-- BASE_MAN_SOURCES_PATH: ${BASE_MAN_SOURCES_PATH}")

# PLACEHOLDER-END #
