# PLACEHOLDER-BEGIN #
MESSAGE("-- python variables.cmake")

SET (PYTHON_SH_SOURCES_PATH ${MAIN_SH_SOURCES_PATH}/python)
SET (PYTHON_SH_SOURCES_BIN_PATH ${PYTHON_SH_SOURCES_PATH}/bin)

# PLACEHOLDER-END #
