.TH smi-argo-location "1" "May 2026" "SMI Toolset" "SMI Infra Command"
.SH NAME
smi-argo-location \- Print the SMI Argo Workflows YAML library directory
.SH SYNOPSIS
.B smi-argo-location
.SH DESCRIPTION
.PP
.B smi-argo-location
prints the absolute path to the Argo Workflows YAML template directory within the SMI library location.
The directory is \fB$(smi-lib-location)/argo\fR, typically \fB/opt/setmy.info/lib/argo\fR on Linux.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-argo-location bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-lib-location (1),
.BR smi-k8s-location (1)
