export CLOJURE_SCRIPT_HOME=/opt/clojurescript
export CLOJURE_SCRIPT_BIN_DIR=${CLOJURE_SCRIPT_HOME}/bin
export CLOJURE_SCRIPT_LIB_DIR=${CLOJURE_SCRIPT_HOME}/lib
export CLOJURE_SCRIPT_JAR=${CLOJURE_SCRIPT_LIB_DIR}/cljs.jar
export PATH=${CLOJURE_SCRIPT_BIN_DIR}:${PATH}
