.TH example "1" "Februar 2023" "quicklisp-setup Man 1.0.0" "quicklisp-setup"
.SH NAME
quicklisp-setup \- root user quicklisp download tool.
.SH SYNOPSIS
.B quicklisp-setup
.SH DESCRIPTION
Downloads quicklisp under \fB/opt/quicklisp/lib\fR
.SH AUTHOR
Command written by Imre Tabur.
Documentation writen by Imre Tabur.
.SH "REPORTING BUGS"
Report example bugs to bug\ info@setmy.info
.SH "SEE ALSO"
See also
.B another.command.
Manual is maintained as a Texinfo manual.
.B some another tools \(aqxxx.command invocation\(aq
.PP
should give you access to the complete manual.
