.TH example "1" "February 2019" "Example Man 1.0.0" "Example Man Command"
.SH NAME
example \- short description
.SH SYNOPSIS
.B example
[\fIxxxx\fR]... [\fIyyyyy\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
More description. More and more and more.
The command does something with \fB\-part xxx\fR or \fB\-\-part yyyy\fR.
.PP
Some additional description.
.PP
And some more additional description.
.TP
\fB\-one\fR, \fB\-\-one\fR
do not ignore entries starting with .
.TP
\fB\-two\fR, \fB\-\-two\-two\fR
do not list implied . and ..
.SH OPTIONS
.PP
Description of options.
.SH EXAMPLES
.PP
Examples of usage.
.SH OTHER
.PP
Other relevant information.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report example bugs to \fIimre.tabur@mail.ee\fR
.SH "SEE ALSO"
.PP
See also
.B another.command
manual. The manual is maintained as a Texinfo manual.
.B some another tools
.PP
The command \fBxxx.command\fR invocation
should give you access to the complete manual.
