ARCH=`uname -m`
RELEASE=13.0-RELEASE
RELEASE_RESOURCE_URL=http://ftp.freebsd.org/pub/FreeBSD/releases
ARCH_RESOURCE_URL=${RELEASE_RESOURCE_URL}/${ARCH}
RELEASE_RESOURCE_URL=${ARCH_RESOURCE_URL}/${RELEASE}
