PROVIDER_HOME_DIR=~/.${PROVIDER}
HOME_PACKAGES_DIR=${PROVIDER_HOME_DIR}/packages

sbcl_func() {
  SBCL_VERSION=2.3.8
  SBCL_DIR_NAME=sbcl-${SBCL_VERSION}-x86-64-linux-binary
  SBCL_TAR_FILE_NAME=${SBCL_DIR_NAME}.tar
  SBCL_TAR_BZ2_FILE_NAME=${SBCL_TAR_FILE_NAME}.bz2
  SBCL_TAR_BZ2_FILE_URL=http://prdownloads.sourceforge.net/sbcl/${SBCL_TAR_BZ2_FILE_NAME}
}
jdk_func() {
  JDK_VERSION=20.0.2
  JDK_HASH=6e380f22cbe7469fa75fb448bd903d8e
  JDK_URI_NR_PART=9
  JDK_DIR_NAME=jdk-${JDK_VERSION}
  JDK_NAME_PREFIX=openjdk-${JDK_VERSION}
  JDK_TAR_FILE_NAME=${JDK_NAME_PREFIX}_linux-x64_bin.tar
  JDK_TAR_GZ_FILE_NAME=${JDK_TAR_FILE_NAME}.gz
  JDK_TAR_GZ_FILE_URL=https://download.java.net/java/GA/jdk${JDK_VERSION}/${JDK_HASH}/${JDK_URI_NR_PART}/GPL/${JDK_TAR_GZ_FILE_NAME}
}

zulu_jdk_func() {
  # Zulu JDK
  ZULU_JDK17_VERSION=17.44.15
  ZULU_JDK17_BASE_VERSION=17.0.8
  ZULU_JDK17_DIR_NAME=zulu${JDK17_VERSION}-ca-crac-jdk${JDK17_BASE_VERSION}-linux_x64
  ZULU_JDK17_NAME_PREFIX=zulu${JDK17_VERSION}-ca-crac-jdk${JDK17_BASE_VERSION}
  ZULU_JDK17_TAR_FILE_NAME=${JDK17_NAME_PREFIX}-linux_x64.tar
  ZULU_JDK17_TAR_GZ_FILE_NAME=${JDK17_TAR_FILE_NAME}.gz
  ZULU_JDK17_TAR_GZ_FILE_URL=https://cdn.azul.com/zulu/bin/${JDK17_TAR_GZ_FILE_NAME}
}

jdk17_func() {
  JDK17_VERSION=17.0.2
  JDK17_HASH_PART=dfd4a8d0985749f896bed50d7138ee7f
  JDK17_NUMERIC_PART=8
  JDK17_DIR_NAME=jdk-${JDK17_VERSION}
  JDK17_NAME_PREFIX=openjdk-${JDK17_VERSION}
  JDK17_TAR_FILE_NAME=${JDK17_NAME_PREFIX}_linux-x64_bin.tar
  JDK17_TAR_GZ_FILE_NAME=${JDK17_TAR_FILE_NAME}.gz
  JDK17_TAR_GZ_FILE_URL=https://download.java.net/java/GA/${JDK17_VERSION}/${JDK17_HASH_PART}/${JDK17_NUMERIC_PART}/GPL/${JDK17_TAR_GZ_FILE_NAME}
}

tomcat_func() {
  TOMCAT_MAJOR_VERSION=10
  TOMCAT_VERSION=${TOMCAT_MAJOR_VERSION}.1.13
  TOMCAT_DIR_NAME=apache-tomcat-${TOMCAT_VERSION}
  TOMCAT_TAR_FILE_NAME=${TOMCAT_DIR_NAME}.tar
  TOMCAT_TAR_GZ_FILE_NAME=${TOMCAT_TAR_FILE_NAME}.gz
  TOMCAT_TAR_GZ_FILE_URL=https://dlcdn.apache.org/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_VERSION}/bin/${TOMCAT_TAR_GZ_FILE_NAME}
}

zeebe_func() {
  ZEEBE_VERSION=8.0.21
  ZEEBE_DIR_NAME=camunda-zeebe-${ZEEBE_VERSION}
  ZEEBE_TAR_FILE_NAME=${ZEEBE_DIR_NAME}.tar
  ZEEBE_TAR_GZ_FILE_NAME=${ZEEBE_TAR_FILE_NAME}.gz
  ZEEBE_TAR_GZ_FILE_URL=https://github.com/camunda/zeebe/releases/download/${ZEEBE_VERSION}/${ZEEBE_TAR_GZ_FILE_NAME}
}

infinispan_func() {
  INFINISPAN_VERSION=14.0.13
  INFINISPAN_DIR_NAME=infinispan-server-${INFINISPAN_VERSION}.Final
  INFINISPAN_ZIP_FILE_NAME=${INFINISPAN_DIR_NAME}.zip
  INFINISPAN_ZIP_FILE_URL=https://downloads.jboss.org/infinispan/${INFINISPAN_VERSION}.Final/${INFINISPAN_ZIP_FILE_NAME}
}

hsqldb_func() {
  HSQLDB_VERSION=2.7.2
  HSQLDB_DIR_NAME=hsqldb-${HSQLDB_VERSION}
  HSQLDB_ZIP_FILE_NAME=${HSQLDB_DIR_NAME}.zip
  HSQLDB_ZIP_FILE_URL=https://altushost-swe.dl.sourceforge.net/project/hsqldb/hsqldb/hsqldb_2_7/${HSQLDB_ZIP_FILE_NAME}
}

nodejs_func() {
  NODE_VERSION=18.17.1
  NODE_DIR_NAME=node-v${NODE_VERSION}-linux-x64
  NODE_TAR_FILE_NAME=${NODE_DIR_NAME}.tar
  NODE_TAR_XZ_FILE_NAME=${NODE_TAR_FILE_NAME}.xz
  NODE_TAR_XZ_FILE_URL=https://nodejs.org/dist/v${NODE_VERSION}/${NODE_TAR_XZ_FILE_NAME}
}

maven_func() {
  MAVEN_VERSION=3.9.4
  MAVEN_DIR_NAME=apache-maven-${MAVEN_VERSION}
  MAVEN_TAR_FILE_NAME=${MAVEN_DIR_NAME}-bin.tar
  MAVEN_TAR_GZ_FILE_NAME=${MAVEN_TAR_FILE_NAME}.gz
  MAVEN_TAR_GZ_FILE_URL=https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
}

gradle_func() {
  GRADLE_VERSION=8.3
  GRADLE_DIR_NAME=gradle-${GRADLE_VERSION}
  GRADLE_ZIP_FILE_NAME=${GRADLE_DIR_NAME}-bin.zip
  GRADLE_ZIP_FILE_URL=https://services.gradle.org/distributions/${GRADLE_ZIP_FILE_NAME}
}

cmake_func() {
  CMAKE_VERSION=3.27.4
  CMAKE_DIR_NAME=cmake-${CMAKE_VERSION}-linux-x86_64
  CMAKE_TAR_FILE_NAME=${CMAKE_DIR_NAME}.tar
  CMAKE_TAR_GZ_FILE_NAME=${CMAKE_TAR_FILE_NAME}.gz
  CMAKE_TAR_GZ_FILE_URL=https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${CMAKE_TAR_GZ_FILE_NAME}
}

julia_func() {
  JULIA_BASE_VERSION=1.9
  JULIA_VERSION=${JULIA_BASE_VERSION}.2
  JULIA_DIR_NAME=julia-${JULIA_VERSION}
  JULIA_TAR_FILE_NAME=${JULIA_DIR_NAME}-linux-x86_64.tar
  JULIA_TAR_GZ_FILE_NAME=${JULIA_TAR_FILE_NAME}.gz
  JULIA_TAR_GZ_FILE_URL=https://julialang-s3.julialang.org/bin/linux/x64/${JULIA_BASE_VERSION}/${JULIA_TAR_GZ_FILE_NAME}
}

go_func() {
  GO_VERSION=1.21.1
  GO_DIR_NAME=go
  GO_TAR_FILE_NAME=${GO_DIR_NAME}${GO_VERSION}.linux-amd64.tar
  GO_TAR_GZ_FILE_NAME=${GO_TAR_FILE_NAME}.gz
  GO_TAR_GZ_FILE_URL=https://go.dev/dl/${GO_TAR_GZ_FILE_NAME}
}

dvc_func() {
  DVC_VERSION=3.19.0
  DVC_DIR_NAME=dvc-${DVC_VERSION}-1.x86_64
  DVC_RPM_FILE_NAME=${DVC_DIR_NAME}.rpm
  DVC_RPM_FILE_URL=https://s3-us-east-2.amazonaws.com/dvc-s3-repo/rpm/${DVC_RPM_FILE_NAME}
}

jenkins_func() {
  JENKINS_VERSION=2.414.1
  JENKINS_DIR_NAME=jenkins
  JENKINS_WAR_FILE_NAME=${JENKINS_DIR_NAME}.war
  JENKINS_WAR_FILE_URL=https://ftp.halifax.rwth-aachen.de/jenkins/war-stable/${JENKINS_VERSION}/${JENKINS_WAR_FILE_NAME}
}

jenkins_home_func() {
  JENKINS_HOME_VERSION=1.0.1
  JENKINS_HOME_DIR_NAME=jenkins
  JENKINS_HOME_TAR_FILE_NAME=${JENKINS_HOME_DIR_NAME}-${JENKINS_HOME_VERSION}.tar
  JENKINS_HOME_TAR_GZ_FILE_NAME=${JENKINS_HOME_TAR_FILE_NAME}.gz
}

createHomePackagesFolder() {
    mkdir -p ${HOME_PACKAGES_DIR}
}

installPackages() {
    INSTALLABLE_PACKAGES=${*}
    for INSTALLABLE_PACKAGE in ${INSTALLABLE_PACKAGES}; do
        installPackage ${INSTALLABLE_PACKAGE}
    done
    return
}

installPackage() {
  PACKAGE_NAME=${1}
  ${PACKAGE_NAME}_func
  return
}
