#!/bin/sh

# Copyright (C) 2019, 2020, 2021 Imre Tabur

. `smi-include base.sh`
. `smi-include commons.sh`
. `smi-include freebsd.sh`

JAILS_DIR=`smi-jails-location`

BASE_PACKAGES="base ports src"
BASE_JAIL_DIR=${JAILS_DIR}/base

EXTRACT="tar -xvvf"
DOWNLOAD="wget -c"
PACKAGE="tar cfJ"
ORIGINAL_PAGER=${PAGER}

export PAGER=cat

jailRcConf() {
    echo "sendmail_enable=NONE"
    echo "syslogd_flags=-ss"
    echo "rpcbind_enable=NO"
}

mkdir -p ${JAILS_DIR}
cd ${JAILS_DIR}

chflags -R noschg ${BASE_JAIL_DIR}/* && rm -fR ${BASE_JAIL_DIR}
mkdir -p ${BASE_JAIL_DIR}
for SET in ${BASE_PACKAGES};
do
    ${DOWNLOAD} ${RELEASE_RESOURCE_URL}/${SET}.txz
    ${EXTRACT} ${JAILS_DIR}/${SET}.txz --totals -C ${BASE_JAIL_DIR}
done

jailRcConf > ${BASE_JAIL_DIR}/etc/rc.conf
freebsd-update -b ${BASE_JAIL_DIR} --not-running-from-cron fetch
freebsd-update -b ${BASE_JAIL_DIR} --not-running-from-cron install
pkg -c ${BASE_JAIL_DIR} update -q
pkg -c ${BASE_JAIL_DIR} upgrade -y
pkg -c ${BASE_JAIL_DIR} install -y bash mc nano
pw -R ${BASE_JAIL_DIR} addgroup -n microservice
pw -R ${BASE_JAIL_DIR} adduser microservice -g microservice -d /nonexistent -s /usr/sbin/nologin -c "Microservice nologin user"
${PACKAGE} jail.base-${RELEASE}.txz -C ${BASE_JAIL_DIR} .

export PAGER=${ORIGINAL_PAGER}

cdCurDir

exit 0
