#!/bin/sh

# Copyright 2021 Imre Tabur

CUR_DIR=${PWD}

. `smi-include commons.sh`

# PACKAGE_NAME=
# FROM_DIR=
# HISTORY_DIR=
# DEPLOY_DIR=
# DEPLOY_OWNER=
# DEPLOY_GROUP=
include `smi-etc-location`/smi-scheduled-deploy.sh

deployFiles() {
    FILES=`ls ${FROM_DIR}/*.tar.gz`
    for FILE_PATH_NAME in ${FILES}
    do
	deployTarGzFile ${FILE_PATH_NAME}
    done
}

deployTarGzFile() {
    FILE_PATH_NAME=${1}
    TIMESTAMP=`smi-timestamp`
    if [ -f ${FILE_PATH_NAME} ]
    then
    echo "Processing ${FILE_PATH_NAME}"
    cp ${FILE_PATH_NAME} ${DEPLOY_DIR}
    cd ${DEPLOY_DIR}
    rm -Rf ${DEPLOY_DIR}/${PACKAGE_NAME}
    chown ${DEPLOY_OWNER}:${DEPLOY_GROUP} ${DEPLOY_DIR}/*.tar.gz
    tar xvzf ${DEPLOY_DIR}/${PACKAGE_NAME}*.tar.gz
    mv ${DEPLOY_DIR}/${PACKAGE_NAME}*.tar.gz ${HISTORY_DIR}/${TIMESTAMP}-${PACKAGE_NAME}*.tar.gz
    rm -f ${FILE_PATH_NAME}
    fi
    cd ${CUR_DIR}
}
test -f ${FROM_DIR}/*.tar.gz && deployFiles

exit $?
