#!/bin/sh

# Copyright (C) 2021 Imre Tabur

. `smi-include base.sh`

OS=`uname`
CUR_DIR=`pwd`
COMMAND=${0}
PARAMETERS=${@}

goSudo() {
    CMD_USER=`whoami`
    if [ "${CMD_USER}" != "root" ]; then
        sudo ${COMMAND} ${PARAMETERS}
        exit ${?}
    fi
    return
}

LinuxBSDUpdate() {
    echo "=== Linux (CentOS/Fedora/Rocky) update ==="
    dnf update -y
}

FreeBSDUpdate() {
    echo "=== FreeBSD update ==="
    ORIGINAL_PAGER=${PAGER}
    export PAGER=cat
    freebsd-update --not-running-from-cron fetch
    freebsd-update --not-running-from-cron install
    pkg update -f
    pkg upgrade -y
    # To avoid leap seconds file to be out of date
    service ntpd onefetch
    export PAGER=${ORIGINAL_PAGER}
}

goSudo
${OS}Update

exit 0
