# PLACEHOLDER-BEGIN #
MESSAGE("-- cpp bin.cmake")

#INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/javah/bin.cmake)
#INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/library/bin.cmake)
#INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/main/bin.cmake)

# PLACEHOLDER-END #
