# PLACEHOLDER-BEGIN #
MESSAGE("-- cpp lib.cmake")

#INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/javah/lib.cmake)
#INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/library/lib.cmake)
#INCLUDE_CMAKE_FILE(${MAIN_CPP_CMAKE_PATH}/main/lib.cmake)

# PLACEHOLDER-END #
