.TH smi-docker-prepare "1" "October 2025" "SMI Toolset 0.100.0" "SMI Docker Command"
.SH NAME
smi-docker-prepare \- Prepare local build environment for Docker
.SH SYNOPSIS
.B smi-docker-prepare
.SH DESCRIPTION
.PP
.B smi-docker-prepare
executes the \fBdocker_prepare\fR function from the local \fBbuild.sh\fR script. It is used to perform any necessary pre-build steps (e.g., gathering artifacts) before running \fBsmi-docker-build\fR.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report smi-docker-prepare bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-docker-build (1)
