.TH smi-jail-delete "1" "October 2025" "SMI Toolset 0.100.0" "SMI Jail Command"
.SH NAME
smi-jail-delete \- Delete a FreeBSD jail
.SH SYNOPSIS
.B smi-jail-delete
.I JAIL_NAME
.SH DESCRIPTION
.PP
.B smi-jail-delete
removes the specified FreeBSD \fIJAIL_NAME\fR from the SMI jails directory.
It uses \fBchflags -R noschg\fR to ensure that system immutable flags are removed before attempting to delete the directory with \fBrm -rf\fR.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-jail-delete bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-jail (1),
.BR smi-jails-location (1)

