.TH smi-jails-location "1" "October 2025" "SMI Toolset 0.100.0" "SMI Jail Command"
.SH NAME
smi-jails-location \- Print the SMI jails directory location
.SH SYNOPSIS
.B smi-jails-location
.SH DESCRIPTION
.PP
.B smi-jails-location
prints the absolute path to the directory where FreeBSD jails are stored, typically \fB/var/jails\fR.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report smi-jails-location bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-jail (1)

