.TH difftool "1" "February 2026" "SMI Toolset 0.100.0" "SMI VCS Command"
.SH NAME
difftool \- git difftool in directory mode
.SH SYNOPSIS
.B difftool
.RI [ ARGUMENTS... ]
.SH DESCRIPTION
.PP
.B difftool
is a wrapper script for \fBgit difftool -d\fR, which launches a visual diff tool to resolve merge conflicts or view differences between directory trees.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report difftool bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR git-difftool (1)
