.TH difftoolc "1" "February 2026" "SMI Toolset 0.100.0" "SMI VCS Command"
.SH NAME
difftoolc \- git difftool for cached changes
.SH SYNOPSIS
.B difftoolc
.RI [ ARGUMENTS... ]
.SH DESCRIPTION
.PP
.B difftoolc
is a wrapper script for \fBdifftool --cached\fR. It allows viewing differences for staged (cached) changes using a visual diff tool.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report difftoolc bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR difftool (1),
.BR git-difftool (1)
