.TH difftools "1" "February 2026" "SMI Toolset 0.100.0" "SMI VCS Command"
.SH NAME
difftools \- git difftool for stashed changes
.SH SYNOPSIS
.B difftools
.SH DESCRIPTION
.PP
.B difftools
is a wrapper script for \fBgit difftool -d ..stash@{0}\fR. It allows viewing the differences in the most recent stash using a visual diff tool.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Junie.
.SH "REPORTING BUGS"
.PP
Report difftools bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR git-difftool (1),
.BR git-stash (1)
