#!/bin/sh

. `smi-include base.sh`
. `smi-include commons.sh`
. `smi-include stealer.include.sh`
. `smi-include stealer.commons.sh`
. `smi-include stealer.vcs.include.sh`

case $COMMAND_NAME in
	smi-stealer)
            COMMAND_NAME="smi_stealer"
            ;;
	*)
            echo "Sorry, I don't understand"
            ;;
esac

executeCommand $@
COMMAND_RESULT=${?}

cdCurDir

exit ${COMMAND_RESULT}
