#!/bin/sh

# Copyright 2019 Imre Tabur <imre.tabur@eesti.ee>

. `smi-include base.sh`
OS=`uname`

FreeBSDVarLocation() {
    echo `smi-location`/var/${PROVIDER}
}

LinuxVarLocation() {
    echo /var/opt/${PROVIDER}
}

${OS}VarLocation

exit ${?}