call %LOADER_CMD% jdk
call %LOADER_CMD% mvn
call %LOADER_CMD% ant
call %LOADER_CMD% gradle
call %LOADER_CMD% node
call %LOADER_CMD% groovy
call %LOADER_CMD% mn
call %LOADER_CMD% grails
call %LOADER_CMD% jfx
call %LOADER_CMD% python
call %LOADER_CMD% smi
call %LOADER_CMD% leiningen
call %LOADER_CMD% cmake
