set PYTHON_HOME=%PUB_DIR%\python
set PYTHON_BIN_DIR=%PYTHON_HOME%

set PYTHON_SCRIPTS_DIR=%PYTHON_HOME%\Scripts
set PYTHON_SCRIPTS_BIN_DIR=%PYTHON_SCRIPTS_DIR%

REM set PIP_HOME=%PYTHON_SCRIPTS_BIN_DIR%
REM set PIP_BIN_DIR=%PIP_HOME%

set PATH=%PYTHON_SCRIPTS_BIN_DIR%;%PYTHON_BIN_DIR%;%PATH%