.TH smi-start-diskless "1" "August 2026" "SMI Toolset" "SMI Diskless Command"
.SH NAME
smi-start-diskless \- Restart the servers the diskless machines boot from
.SH SYNOPSIS
.B smi-start-diskless
.SH DESCRIPTION
.PP
.B smi-start-diskless
restarts the services a diskless machine needs to boot and to run, in the
order they depend on each other:
.IP 1.
.B rpcbind
.IP 2.
.B nfs-server
.IP 3.
.B tftp.socket
.IP 4.
.B dhcpd
.PP
The services are enabled and started by
.BR smi-make-diskless (1)
already.
This command is for restarting them after a change of the configuration of the
server that was not made by the diskless commands.
.PP
A change of the exports alone does not need a restart, it is applied by
.BR smi-make-diskless (1)
and
.BR smi-diskless-remove (1)
with
.BR "exportfs -r" .
.SH AUTHOR
.PP
Command written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-start-diskless bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.BR smi-stop-diskless (1),
.BR smi-make-diskless (1)
