.TH smi-diskless-passwd "1" "August 2026" "SMI Toolset" "SMI Diskless Command"
.SH NAME
smi-diskless-passwd \- Set a user password in a diskless installation
.SH SYNOPSIS
.B smi-diskless-passwd
.I DISKLESS_NAME
.I USER_NAME
.SH DESCRIPTION
.PP
.B smi-diskless-passwd
sets the password of
.I USER_NAME
in the installation
.IR DISKLESS_NAME .
.PP
The command runs
.BR passwd (8)
in the chroot of the installation, with the kernel file systems mounted, see
.BR smi-diskless-chroot (1),
and asks for the password on the terminal.
The password is never given on the command line.
.PP
Use
.B root
as the user name to set the root password of the diskless machine.
.SH EXAMPLES
.PP
Set the password of a user:
.RS
.B smi-diskless-passwd ws-01 has
.RE
.PP
Set the root password of the installation:
.RS
.B smi-diskless-passwd ws-01 root
.RE
.SH AUTHOR
.PP
Command written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-diskless-passwd bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.BR smi-make-diskless (1),
.BR smi-diskless-useradd (1),
.BR smi-diskless-chroot (1)
