.TH smi-diskless-useradd "1" "August 2026" "SMI Toolset" "SMI Diskless Command"
.SH NAME
smi-diskless-useradd \- Add a user to a diskless installation
.SH SYNOPSIS
.B smi-diskless-useradd
.I DISKLESS_NAME
.I USER_NAME
.SH DESCRIPTION
.PP
.B smi-diskless-useradd
adds the user
.I USER_NAME
to the installation
.IR DISKLESS_NAME .
.PP
The command runs
.BR useradd (8)
in the chroot of the installation, with the kernel file systems mounted, see
.BR smi-diskless-chroot (1).
.PP
The home directory is created below
.B /home
of the chroot.
That directory is not the one the client uses: the client mounts the exported
.B home
directory of the installation over it.
.PP
The user has no password until one is set with
.BR smi-diskless-passwd (1).
.SH EXAMPLES
.PP
.RS
.nf
smi-diskless-useradd ws-01 has
smi-diskless-passwd ws-01 has
.fi
.RE
.SH AUTHOR
.PP
Command written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-diskless-useradd bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.BR smi-make-diskless (1),
.BR smi-diskless-passwd (1),
.BR smi-diskless-chroot (1)
