.TH smi-selenium-standalone "1" "October 2025" "SMI Toolset 0.100.0" "SMI Selenium Command"
.SH NAME
smi-selenium-standalone \- Start Selenium Grid in Standalone mode
.SH SYNOPSIS
.B smi-selenium-standalone
.SH DESCRIPTION
.PP
.B smi-selenium-standalone
starts a Selenium Grid in Standalone mode, where all components (Hub and Node) run in a single process.
It uses the Selenium standalone JAR file found in the SMI library location.
It requires the \fBSELENIUM_JAR_FILE_NAME\fR environment variable to be set to the name of the Selenium JAR file.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-selenium-standalone bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-selenium-hub (1),
.BR smi-selenium-node (1)
