.TH smi-selenium-hub "1" "October 2025" "SMI Toolset 0.100.0" "SMI Selenium Command"
.SH NAME
smi-selenium-hub \- Start a Selenium Grid Hub
.SH SYNOPSIS
.B smi-selenium-hub
.SH DESCRIPTION
.PP
.B smi-selenium-hub
starts a Selenium Grid Hub using the Selenium standalone JAR file found in the SMI library location.
It requires the \fBSELENIUM_JAR_FILE_NAME\fR environment variable to be set to the name of the Selenium JAR file.
.SH AUTHOR
.PP
Command written by Imre Tabur.
Documentation written by Imre Tabur.
.SH "REPORTING BUGS"
.PP
Report smi-selenium-hub bugs to \fIinfo@setmy.info\fR
.SH "SEE ALSO"
.PP
.BR smi-selenium-node (1),
.BR smi-selenium-standalone (1)
